apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-output
spec:
  results:
    - name: TEST_OUTPUT
      description: Test output
  params:
    - default: "SUCCESS"
      name: RESULT
      description: Test result to be generated
  steps:
    - image: quay.io/redhat-appstudio/hacbs-test:stable
      script: |
        echo "Namaste"
        sleep 60

        TEST_OUTPUT=$(jq -rc --arg date $(date +%s) --arg RESULT $(params.RESULT) --null-input \
          '{result: $RESULT, timestamp: $date, failures: 0, successes: 0, warnings: 0}')
        echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)
