apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: integration-resolver-pipeline-pass
spec:
  tasks:
    - name: task-success
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/dheerajodha/integration-examples 
          - name: revision
            value: test-delay
          - name: pathInRepo
            value: tasks/test_output.yaml
      params:
        - name: RESULT
          value: SUCCESS
    - name: task-success-2
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/dheerajodha/integration-examples 
          - name: revision
            value: test-delay
          - name: pathInRepo
            value: tasks/test_output.yaml
      params:
        - name: RESULT
          value: SUCCESS
    - name: task-skipped
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/dheerajodha/integration-examples 
          - name: revision
            value: test-delay
          - name: pathInRepo
            value: tasks/test_output.yaml
      params:
        - name: RESULT
          value: SKIPPED
